# Generated by Django 4.1.7 on 2024-04-30 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipservices',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
