# Generated by Django 4.1.7 on 2024-05-02 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricing',
            name='slug',
            field=models.SlugField(default='', max_length=100, unique=True),
        ),
    ]
