# Generated by Django 4.1.7 on 2024-04-30 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0002_alter_membershipservices_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipplans',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='membershipplans',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
