# Generated by Django 4.1.7 on 2024-05-04 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0003_alter_subscriptionplan_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='subscription_id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
