# Generated by Django 4.1.7 on 2024-04-30 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0003_membershipplans_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membershipplans',
            options={'ordering': ['created_at'], 'verbose_name': 'Membership Plan', 'verbose_name_plural': 'Membership Plans'},
        ),
        migrations.AlterModelOptions(
            name='membershipservices',
            options={'ordering': ['id'], 'verbose_name': 'Membership Service', 'verbose_name_plural': 'Membership Services'},
        ),
        migrations.AlterModelOptions(
            name='subscriptionplan',
            options={},
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='subscription_id',
        ),
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('half_yearly', 'Half Yearly'), ('yearly', 'Yearly')], default='monthly', max_length=20, verbose_name='Package')),
                ('price', models.FloatField(default=0.0, verbose_name='Price')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('membership_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memberships.membershipplans', verbose_name='Membership Plan')),
            ],
            options={
                'verbose_name': 'Pricing',
                'verbose_name_plural': 'Pricings',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='pricing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='memberships.pricing'),
        ),
    ]
