# Generated by Django 4.1.7 on 2024-04-30 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0004_alter_membershipplans_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricing',
            name='days',
            field=models.IntegerField(default=30, verbose_name='Days'),
        ),
    ]
