# Generated by Django 4.1.7 on 2024-04-30 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0005_pricing_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
